# Finetuning-friendly settings for GTX 1650 (4 GB) on Penn-Fudan
# Optimizer & schedule
lr0: 0.0015
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 2.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1

# Loss gains
box: 7.5
cls: 0.5
dfl: 1.5

# Light aug for small dataset
hsv_h: 0.015
hsv_s: 0.5
hsv_v: 0.4
degrees: 5.0
translate: 0.05
scale: 0.10
shear: 1.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.0
mixup: 0.0
copy_paste: 0.0

# Regularization
label_smoothing: 0.0
